# mint builtin function table
# generated by mkfunctbl

.xref mint_start
FUNC_ADDR_BASE: .reg mint_start
FUNC_NAME_BITS: .equ 12
FUNC_ADDR_BITS: .equ 20

.data

X: .reg FUNC_ADDR_BASE
.quad
FuncAddrTable:
  .dc.l (s000-S)<<20+＆16color_brightness_decrement-X
  .dc.l (s001-S)<<20+＆16color_brightness_increment-X
  .dc.l (s002-S)<<20+＆16color_palet_set-X
  .dc.l (s003-S)<<20+＆64kcolor_palet_set-X
  .dc.l (s004-S)<<20+＆arc_exist-X
  .dc.l (s005-S)<<20+＆ask_yn-X
  .dc.l (s006-S)<<20+＆beep-X
  .dc.l (s007-S)<<20+＆bell-X
  .dc.l (s008-S)<<20+＆break-X
  .dc.l (s009-S)<<20+＆brightness_decrement-X
  .dc.l (s010-S)<<20+＆brightness_increment-X
  .dc.l (s011-S)<<20+＆cache_off-X
  .dc.l (s012-S)<<20+＆cache_on-X
  .dc.l (s013-S)<<20+＆cal-X
  .dc.l (s014-S)<<20+＆cd-X
  .dc.l (s015-S)<<20+＆cdjp-X
  .dc.l (s016-S)<<20+＆change_drive-X
  .dc.l (s017-S)<<20+＆change_drive_menu-X
  .dc.l (s018-S)<<20+＆chdir-X
  .dc.l (s019-S)<<20+＆chdir_to_opposite_window-X
  .dc.l (s020-S)<<20+＆chdir_to_parent-X
  .dc.l (s021-S)<<20+＆chdir_to_registered_path_menu-X
  .dc.l (s022-S)<<20+＆chmod-X
  .dc.l (s023-S)<<20+＆clear_and_redraw-X
  .dc.l (s024-S)<<20+＆clear_exec_screen-X
  .dc.l (s025-S)<<20+＆clear_gvram-X
  .dc.l (s026-S)<<20+＆clear_mark-X
  .dc.l (s027-S)<<20+＆clear_path_stack-X
  .dc.l (s028-S)<<20+＆clear_text-X
  .dc.l (s029-S)<<20+＆command_history-X
  .dc.l (s030-S)<<20+＆command_history_menu-X
  .dc.l (s031-S)<<20+＆cont_music-X
  .dc.l (s032-S)<<20+＆continue-X
  .dc.l (s033-S)<<20+＆continue_music-X
  .dc.l (s034-S)<<20+＆copy-X
  .dc.l (s035-S)<<20+＆copy_to_history_menu-X
  .dc.l (s036-S)<<20+＆copy_to_registered_path_menu-X
  .dc.l (s037-S)<<20+＆cp-X
  .dc.l (s038-S)<<20+＆cpu_power-X
  .dc.l (s039-S)<<20+＆crt_write_disable-X
  .dc.l (s040-S)<<20+＆cursor_down-X
  .dc.l (s041-S)<<20+＆cursor_left-X
  .dc.l (s042-S)<<20+＆cursor_opposite_window-X
  .dc.l (s043-S)<<20+＆cursor_right-X
  .dc.l (s044-S)<<20+＆cursor_rolldown-X
  .dc.l (s045-S)<<20+＆cursor_rollup-X
  .dc.l (s046-S)<<20+＆cursor_to_bottom-X
  .dc.l (s047-S)<<20+＆cursor_to_home-X
  .dc.l (s048-S)<<20+＆cursor_to_parent-X
  .dc.l (s049-S)<<20+＆cursor_up-X
  .dc.l (s050-S)<<20+＆data_cache_off-X
  .dc.l (s051-S)<<20+＆data_cache_on-X
  .dc.l (s052-S)<<20+＆data_title-X
  .dc.l (s053-S)<<20+＆debug-X
  .dc.l (s054-S)<<20+＆del-X
  .dc.l (s055-S)<<20+＆delete-X
  .dc.l (s056-S)<<20+＆describe_key-X
  .dc.l (s057-S)<<20+＆direct_copy-X
  .dc.l (s058-S)<<20+＆direct_move-X
  .dc.l (s059-S)<<20+＆drive_check-X
  .dc.l (s060-S)<<20+＆drive_decrement-X
  .dc.l (s061-S)<<20+＆drive_increment-X
  .dc.l (s062-S)<<20+＆echo-X
  .dc.l (s063-S)<<20+＆edit_env_variable-X
  .dc.l (s064-S)<<20+＆edit_volume_name-X
  .dc.l (s065-S)<<20+＆eject-X
  .dc.l (s066-S)<<20+＆else-X
  .dc.l (s067-S)<<20+＆else_if-X
  .dc.l (s068-S)<<20+＆elsif-X
  .dc.l (s069-S)<<20+＆end-X
  .dc.l (s070-S)<<20+＆endm-X
  .dc.l (s071-S)<<20+＆equ-X
  .dc.l (s072-S)<<20+＆eval-X
  .dc.l (s073-S)<<20+＆exchange_current-X
  .dc.l (s074-S)<<20+＆exchange_windows-X
  .dc.l (s075-S)<<20+＆exec_j_special_entry-X
  .dc.l (s076-S)<<20+＆exec_registered_command_menu-X
  .dc.l (s077-S)<<20+＆execute_binary-X
  .dc.l (s078-S)<<20+＆exist-X
  .dc.l (s079-S)<<20+＆ext_exec-X
  .dc.l (s080-S)<<20+＆ext_exec_or_chdir-X
  .dc.l (s081-S)<<20+＆ext_help-X
  .dc.l (s082-S)<<20+＆fade_music-X
  .dc.l (s083-S)<<20+＆fadeout_music-X
  .dc.l (s084-S)<<20+＆file_check-X
  .dc.l (s085-S)<<20+＆file_compare-X
  .dc.l (s086-S)<<20+＆file_match-X
  .dc.l (s087-S)<<20+＆foreach-X
  .dc.l (s088-S)<<20+＆get_color_mode-X
  .dc.l (s089-S)<<20+＆get_media_byte-X
  .dc.l (s090-S)<<20+＆get_music_status-X
  .dc.l (s091-S)<<20+＆get_volume_name-X
  .dc.l (s092-S)<<20+＆getsec-X
  .dc.l (s093-S)<<20+＆go_screen_saver-X
  .dc.l (s094-S)<<20+＆goto_cursor-X
  .dc.l (s095-S)<<20+＆grow_window-X
  .dc.l (s096-S)<<20+＆gvon-X
  .dc.l (s097-S)<<20+＆gvram_off-X
  .dc.l (s098-S)<<20+＆gvram_on-X
  .dc.l (s099-S)<<20+＆gvram_text_blend_off-X
  .dc.l (s100-S)<<20+＆gvram_text_blend_on-X
  .dc.l (s101-S)<<20+＆gvram_to_monochrome-X
  .dc.l (s102-S)<<20+＆half-X
  .dc.l (s103-S)<<20+＆i_search-X
  .dc.l (s104-S)<<20+＆if-X
  .dc.l (s105-S)<<20+＆incremental_search-X
  .dc.l (s106-S)<<20+＆information-X
  .dc.l (s107-S)<<20+＆input-X
  .dc.l (s108-S)<<20+＆instruction_cache_off-X
  .dc.l (s109-S)<<20+＆instruction_cache_on-X
  .dc.l (s110-S)<<20+＆iocs-X
  .dc.l (s111-S)<<20+＆iocs_home-X
  .dc.l (s112-S)<<20+＆is_mark-X
  .dc.l (s113-S)<<20+＆is_mintarc-X
  .dc.l (s114-S)<<20+＆is_mount-X
  .dc.l (s115-S)<<20+＆iso9660-X
  .dc.l (s116-S)<<20+＆keep_check-X
  .dc.l (s117-S)<<20+＆key_wait-X
  .dc.l (s118-S)<<20+＆last-X
  .dc.l (s119-S)<<20+＆load_path_history-X
  .dc.l (s120-S)<<20+＆local_path-X
  .dc.l (s121-S)<<20+＆look_file-X
  .dc.l (s122-S)<<20+＆lzh_selector-X
  .dc.l (s123-S)<<20+＆madoka-X
  .dc.l (s124-S)<<20+＆make_dir_and_move-X
  .dc.l (s125-S)<<20+＆make_dirs-X
  .dc.l (s126-S)<<20+＆maketmp-X
  .dc.l (s127-S)<<20+＆mark-X
  .dc.l (s128-S)<<20+＆mark_all-X
  .dc.l (s129-S)<<20+＆mark_all_files-X
  .dc.l (s130-S)<<20+＆mark_forward-X
  .dc.l (s131-S)<<20+＆mark_reverse-X
  .dc.l (s132-S)<<20+＆mark_upper-X
  .dc.l (s133-S)<<20+＆mask-X
  .dc.l (s134-S)<<20+＆mask_regexp-X
  .dc.l (s135-S)<<20+＆match-X
  .dc.l (s136-S)<<20+＆max-X
  .dc.l (s137-S)<<20+＆md-X
  .dc.l (s138-S)<<20+＆menu-X
  .dc.l (s139-S)<<20+＆mioff-X
  .dc.l (s140-S)<<20+＆mion-X
  .dc.l (s141-S)<<20+＆mkdir-X
  .dc.l (s142-S)<<20+＆mono-X
  .dc.l (s143-S)<<20+＆move-X
  .dc.l (s144-S)<<20+＆move_to_history_menu-X
  .dc.l (s145-S)<<20+＆move_to_registered_path_menu-X
  .dc.l (s146-S)<<20+＆mpu_power-X
  .dc.l (s147-S)<<20+＆msdos-X
  .dc.l (s148-S)<<20+＆newer_file-X
  .dc.l (s149-S)<<20+＆next-X
  .dc.l (s150-S)<<20+＆nop-X
  .dc.l (s151-S)<<20+＆older_file-X
  .dc.l (s152-S)<<20+＆online_switch-X
  .dc.l (s153-S)<<20+＆palet0_down-X
  .dc.l (s154-S)<<20+＆palet0_set-X
  .dc.l (s155-S)<<20+＆palet0_system-X
  .dc.l (s156-S)<<20+＆palet0_up-X
  .dc.l (s157-S)<<20+＆path_history_menu-X
  .dc.l (s158-S)<<20+＆pause_music-X
  .dc.l (s159-S)<<20+＆pdx_filename-X
  .dc.l (s160-S)<<20+＆play_music-X
  .dc.l (s161-S)<<20+＆pop_text-X
  .dc.l (s162-S)<<20+＆popd-X
  .dc.l (s163-S)<<20+＆prchk-X
  .dc.l (s164-S)<<20+＆prefix-X
  .dc.l (s165-S)<<20+＆print-X
  .dc.l (s166-S)<<20+＆pushd-X
  .dc.l (s167-S)<<20+＆quick_exit-X
  .dc.l (s168-S)<<20+＆quit-X
  .dc.l (s169-S)<<20+＆re_mount-X
  .dc.l (s170-S)<<20+＆readline-X
  .dc.l (s171-S)<<20+＆reload-X
  .dc.l (s172-S)<<20+＆ren-X
  .dc.l (s173-S)<<20+＆rename-X
  .dc.l (s174-S)<<20+＆rename_marked_files_or_directory-X
  .dc.l (s175-S)<<20+＆rename_menu-X
  .dc.l (s176-S)<<20+＆reset-X
  .dc.l (s177-S)<<20+＆return-X
  .dc.l (s178-S)<<20+＆reverse_all_file_marks-X
  .dc.l (s179-S)<<20+＆reverse_all_marks-X
  .dc.l (s180-S)<<20+＆rm-X
  .dc.l (s181-S)<<20+＆rnd-X
  .dc.l (s182-S)<<20+＆rotate_gvram_ccw-X
  .dc.l (s183-S)<<20+＆rotate_gvram_cw-X
  .dc.l (s184-S)<<20+＆save_path_history-X
  .dc.l (s185-S)<<20+＆scsi_check-X
  .dc.l (s186-S)<<20+＆scsi_menu-X
  .dc.l (s187-S)<<20+＆set-X
  .dc.l (s188-S)<<20+＆set_brightness_to_half-X
  .dc.l (s189-S)<<20+＆set_brightness_to_max-X
  .dc.l (s190-S)<<20+＆set_crtc-X
  .dc.l (s191-S)<<20+＆set_current_to_opposite-X
  .dc.l (s192-S)<<20+＆set_opposite_window_to_current-X
  .dc.l (s193-S)<<20+＆set_opt-X
  .dc.l (s194-S)<<20+＆set_option-X
  .dc.l (s195-S)<<20+＆setenv-X
  .dc.l (s196-S)<<20+＆shrink_window-X
  .dc.l (s197-S)<<20+＆sleep-X
  .dc.l (s198-S)<<20+＆sort-X
  .dc.l (s199-S)<<20+＆sort_menu-X
  .dc.l (s200-S)<<20+＆source-X
  .dc.l (s201-S)<<20+＆sram_contrast-X
  .dc.l (s202-S)<<20+＆stop_condrv-X
  .dc.l (s203-S)<<20+＆stop_music-X
  .dc.l (s204-S)<<20+＆stop_vdisp-X
  .dc.l (s205-S)<<20+＆strcmp-X
  .dc.l (s206-S)<<20+＆sync-X
  .dc.l (s207-S)<<20+＆tar_selector-X
  .dc.l (s208-S)<<20+＆title_load-X
  .dc.l (s209-S)<<20+＆toggle_drive_information-X
  .dc.l (s210-S)<<20+＆toggle_file_information_mode-X
  .dc.l (s211-S)<<20+＆toggle_interrupt_window-X
  .dc.l (s212-S)<<20+＆toggle_palet_illumination-X
  .dc.l (s213-S)<<20+＆toggle_power_window-X
  .dc.l (s214-S)<<20+＆toggle_screen_saver-X
  .dc.l (s215-S)<<20+＆toggle_window_size-X
  .dc.l (s216-S)<<20+＆touch-X
  .dc.l (s217-S)<<20+＆trap-X
  .dc.l (s218-S)<<20+＆turn_gvram_left_and_right-X
  .dc.l (s219-S)<<20+＆turn_gvram_upside_down-X
  .dc.l (s220-S)<<20+＆twentyone_ignore_case-X
  .dc.l (s221-S)<<20+＆un_mount-X
  .dc.l (s222-S)<<20+＆uncompress-X
  .dc.l (s223-S)<<20+＆unless-X
  .dc.l (s224-S)<<20+＆unset-X
  .dc.l (s225-S)<<20+＆unsetenv-X
  .dc.l (s226-S)<<20+＆v_bell-X
  .dc.l (s227-S)<<20+＆visual_bell-X
  .dc.l (s228-S)<<20+＆wait-X
  .dc.l (s229-S)<<20+＆which-X
  .dc.l (s230-S)<<20+＆window_size-X
  .dc.l (s231-S)<<20+＆zip_selector-X
FuncAddrTableEnd:

FuncNameList:
S:
s000: .dc.b '16color-brightness-decrement',0
s001: .dc.b '16color-brightness-increment',0
s002: .dc.b '16color-palet-set',0
s003: .dc.b '64kcolor-palet-set',0
s004: .dc.b 'arc-exist',0
s005: .dc.b 'ask-yn',0
s006: .dc.b 'beep',0
s007: .dc.b 'bell',0
s008: .dc.b 'break',0
s009: .dc.b 'brightness-decrement',0
s010: .dc.b 'brightness-increment',0
s011: .dc.b 'cache-off',0
s012: .dc.b 'cache-on',0
s013: .dc.b 'cal',0
s014: .dc.b 'cd',0
s015: .dc.b 'cdjp',0
s016: .dc.b 'change-drive',0
s017: .dc.b 'change-drive-menu',0
s018: .dc.b 'chdir',0
s019: .dc.b 'chdir-to-opposite-window',0
s020: .dc.b 'chdir-to-parent',0
s021: .dc.b 'chdir-to-registered-path-menu',0
s022: .dc.b 'chmod',0
s023: .dc.b 'clear-and-redraw',0
s024: .dc.b 'clear-exec-screen',0
s025: .dc.b 'clear-gvram',0
s026: .dc.b 'clear-mark',0
s027: .dc.b 'clear-path-stack',0
s028: .dc.b 'clear-text',0
s029: .dc.b 'command-history',0
s030: .dc.b 'command-history-menu',0
s031: .dc.b 'cont-music',0
s032: .dc.b 'continue',0
s033: .dc.b 'continue-music',0
s034: .dc.b 'copy',0
s035: .dc.b 'copy-to-history-menu',0
s036: .dc.b 'copy-to-registered-path-menu',0
s037: .dc.b 'cp',0
s038: .dc.b 'cpu-power',0
s039: .dc.b 'crt-write-disable',0
s040: .dc.b 'cursor-down',0
s041: .dc.b 'cursor-left',0
s042: .dc.b 'cursor-opposite-window',0
s043: .dc.b 'cursor-right',0
s044: .dc.b 'cursor-rolldown',0
s045: .dc.b 'cursor-rollup',0
s046: .dc.b 'cursor-to-bottom',0
s047: .dc.b 'cursor-to-home',0
s048: .dc.b 'cursor-to-parent',0
s049: .dc.b 'cursor-up',0
s050: .dc.b 'data-cache-off',0
s051: .dc.b 'data-cache-on',0
s052: .dc.b 'data-title',0
s053: .dc.b 'debug',0
s054: .dc.b 'del',0
s055: .dc.b 'delete',0
s056: .dc.b 'describe-key',0
s057: .dc.b 'direct-copy',0
s058: .dc.b 'direct-move',0
s059: .dc.b 'drive-check',0
s060: .dc.b 'drive-decrement',0
s061: .dc.b 'drive-increment',0
s062: .dc.b 'echo',0
s063: .dc.b 'edit-env-variable',0
s064: .dc.b 'edit-volume-name',0
s065: .dc.b 'eject',0
s066: .dc.b 'else',0
s067: .dc.b 'else-if',0
s068: .dc.b 'elsif',0
s069: .dc.b 'end',0
s070: .dc.b 'endm',0
s071: .dc.b 'equ',0
s072: .dc.b 'eval',0
s073: .dc.b 'exchange-current',0
s074: .dc.b 'exchange-windows',0
s075: .dc.b 'exec-j-special-entry',0
s076: .dc.b 'exec-registered-command-menu',0
s077: .dc.b 'execute-binary',0
s078: .dc.b 'exist',0
s079: .dc.b 'ext-exec',0
s080: .dc.b 'ext-exec-or-chdir',0
s081: .dc.b 'ext-help',0
s082: .dc.b 'fade-music',0
s083: .dc.b 'fadeout-music',0
s084: .dc.b 'file-check',0
s085: .dc.b 'file-compare',0
s086: .dc.b 'file-match',0
s087: .dc.b 'foreach',0
s088: .dc.b 'get-color-mode',0
s089: .dc.b 'get-media-byte',0
s090: .dc.b 'get-music-status',0
s091: .dc.b 'get-volume-name',0
s092: .dc.b 'getsec',0
s093: .dc.b 'go-screen-saver',0
s094: .dc.b 'goto-cursor',0
s095: .dc.b 'grow-window',0
s096: .dc.b 'gvon',0
s097: .dc.b 'gvram-off',0
s098: .dc.b 'gvram-on',0
s099: .dc.b 'gvram-text-blend-off',0
s100: .dc.b 'gvram-text-blend-on',0
s101: .dc.b 'gvram-to-monochrome',0
s102: .dc.b 'half',0
s103: .dc.b 'i-search',0
s104: .dc.b 'if',0
s105: .dc.b 'incremental-search',0
s106: .dc.b 'information',0
s107: .dc.b 'input',0
s108: .dc.b 'instruction-cache-off',0
s109: .dc.b 'instruction-cache-on',0
s110: .dc.b 'iocs',0
s111: .dc.b 'iocs-home',0
s112: .dc.b 'is-mark',0
s113: .dc.b 'is-mintarc',0
s114: .dc.b 'is-mount',0
s115: .dc.b 'iso9660',0
s116: .dc.b 'keep-check',0
s117: .dc.b 'key-wait',0
s118: .dc.b 'last',0
s119: .dc.b 'load-path-history',0
s120: .dc.b 'local-path',0
s121: .dc.b 'look-file',0
s122: .dc.b 'lzh-selector',0
s123: .dc.b 'madoka',0
s124: .dc.b 'make-dir-and-move',0
s125: .dc.b 'make-dirs',0
s126: .dc.b 'maketmp',0
s127: .dc.b 'mark',0
s128: .dc.b 'mark-all',0
s129: .dc.b 'mark-all-files',0
s130: .dc.b 'mark-forward',0
s131: .dc.b 'mark-reverse',0
s132: .dc.b 'mark-upper',0
s133: .dc.b 'mask',0
s134: .dc.b 'mask-regexp',0
s135: .dc.b 'match',0
s136: .dc.b 'max',0
s137: .dc.b 'md',0
s138: .dc.b 'menu',0
s139: .dc.b 'mioff',0
s140: .dc.b 'mion',0
s141: .dc.b 'mkdir',0
s142: .dc.b 'mono',0
s143: .dc.b 'move',0
s144: .dc.b 'move-to-history-menu',0
s145: .dc.b 'move-to-registered-path-menu',0
s146: .dc.b 'mpu-power',0
s147: .dc.b 'msdos',0
s148: .dc.b 'newer-file',0
s149: .dc.b 'next',0
s150: .dc.b 'nop',0
s151: .dc.b 'older-file',0
s152: .dc.b 'online-switch',0
s153: .dc.b 'palet0-down',0
s154: .dc.b 'palet0-set',0
s155: .dc.b 'palet0-system',0
s156: .dc.b 'palet0-up',0
s157: .dc.b 'path-history-menu',0
s158: .dc.b 'pause-music',0
s159: .dc.b 'pdx-filename',0
s160: .dc.b 'play-music',0
s161: .dc.b 'pop-text',0
s162: .dc.b 'popd',0
s163: .dc.b 'prchk',0
s164: .dc.b 'prefix',0
s165: .dc.b 'print',0
s166: .dc.b 'pushd',0
s167: .dc.b 'quick-exit',0
s168: .dc.b 'quit',0
s169: .dc.b 're-mount',0
s170: .dc.b 'readline',0
s171: .dc.b 'reload',0
s172: .dc.b 'ren',0
s173: .dc.b 'rename',0
s174: .dc.b 'rename-marked-files-or-directory',0
s175: .dc.b 'rename-menu',0
s176: .dc.b 'reset',0
s177: .dc.b 'return',0
s178: .dc.b 'reverse-all-file-marks',0
s179: .dc.b 'reverse-all-marks',0
s180: .dc.b 'rm',0
s181: .dc.b 'rnd',0
s182: .dc.b 'rotate-gvram-ccw',0
s183: .dc.b 'rotate-gvram-cw',0
s184: .dc.b 'save-path-history',0
s185: .dc.b 'scsi-check',0
s186: .dc.b 'scsi-menu',0
s187: .dc.b 'set',0
s188: .dc.b 'set-brightness-to-half',0
s189: .dc.b 'set-brightness-to-max',0
s190: .dc.b 'set-crtc',0
s191: .dc.b 'set-current-to-opposite',0
s192: .dc.b 'set-opposite-window-to-current',0
s193: .dc.b 'set-opt',0
s194: .dc.b 'set-option',0
s195: .dc.b 'setenv',0
s196: .dc.b 'shrink-window',0
s197: .dc.b 'sleep',0
s198: .dc.b 'sort',0
s199: .dc.b 'sort-menu',0
s200: .dc.b 'source',0
s201: .dc.b 'sram-contrast',0
s202: .dc.b 'stop-condrv',0
s203: .dc.b 'stop-music',0
s204: .dc.b 'stop-vdisp',0
s205: .dc.b 'strcmp',0
s206: .dc.b 'sync',0
s207: .dc.b 'tar-selector',0
s208: .dc.b 'title-load',0
s209: .dc.b 'toggle-drive-information',0
s210: .dc.b 'toggle-file-information-mode',0
s211: .dc.b 'toggle-interrupt-window',0
s212: .dc.b 'toggle-palet-illumination',0
s213: .dc.b 'toggle-power-window',0
s214: .dc.b 'toggle-screen-saver',0
s215: .dc.b 'toggle-window-size',0
s216: .dc.b 'touch',0
s217: .dc.b 'trap',0
s218: .dc.b 'turn-gvram-left-and-right',0
s219: .dc.b 'turn-gvram-upside-down',0
s220: .dc.b 'twentyone-ignore-case',0
s221: .dc.b 'un-mount',0
s222: .dc.b 'uncompress',0
s223: .dc.b 'unless',0
s224: .dc.b 'unset',0
s225: .dc.b 'unsetenv',0
s226: .dc.b 'v-bell',0
s227: .dc.b 'visual-bell',0
s228: .dc.b 'wait',0
s229: .dc.b 'which',0
s230: .dc.b 'window-size',0
s231: .dc.b 'zip-selector',0

.text
